name: run unit tests
on: pull_request
jobs:
  run-unit-tests:
    name: run unit tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes","devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install zoltr and scoringutils
        run: |
          devtools::install_github("reichlab/zoltr")
          devtools::install_github("epiforecasts/scoringutils")
          devtools::install()
        shell: Rscript {0}
      - name: Run unit tests
        run: |
          devtools::test_file("test-date_management.R")
          devtools::test_file("test-score_forecasts.R")
          devtools::test_file("test-load_forecast_files_repo.R")
          devtools::test_file("test-get_model_designations.R")
        shell: Rscript {0}


